version: 0.2

phases:
  install:
    commands:
      - git config --global user.name "mrfrase3"
      - git config --global user.password "$GITHUB_TOKEN"
      - git submodule init
      - git submodule update
      - npm i
  pre_build:
    commands:
      - echo beginning build
  build:
    commands:
      - npm build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/*
