version: 0.2

phases:
  install:
    commands:
      - export API_DOMAIN=$API_DOMAIN
      - git config --global url."https://$GITHUB_TOKEN@github.com/".insteadOf "https://github.com/"
      - git submodule init
      - git submodule update
      - npm i
  pre_build:
    commands:
      # patch pending fix for feathers-vuex
      - git clone -b mrf-fix-174 --single-branch https://github.com/mrfrase3/feathers-vuex.git
      - cd feathers-vuex
      - npm i
      - cd ../
      - rm -rf node_modules/feathers-vuex/lib/*
      - cp -a feathers-vuex/lib/* node_modules/feathers-vuex/lib/
      - npm cache clean --force
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist
