version: 0.2

phases:
  install:
    commands:
      - export API_DOMAIN=$API_DOMAIN
      - npm i
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist
