version: 0.2

phases:
  install:
    commands:
      - npm i
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist
