version: 0.2

phases:
  install:
    commands:
      - mkdir -p ~/.ssh
      - echo "$GITHUB_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
      - git config --global url."git@github.com:".insteadOf "https://github.com/"
      - git submodule init
      - git submodule update
      - npm i
  pre_build:
    commands:
      - echo beginning build
  build:
    commands:
      - npm build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/*
