version: 0.2

phases:
  install:
    commands:
      - git config --global url."https://$GITHUB_TOKEN@github.com/".insteadOf "https://github.com/"
      - git submodule init
      - git submodule update
      - npm i
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist
